# Site Settings
title: "HELO"
author: "Alex Ash"
description: "Agents and LLMs-in-the-stack - Expert insights on AI implementation, automation workflows, and system integration"
url: "https://alpha.helosolutions.ai"
logo: /assets/logo.png

# Social Media
twitter_username: "alexheloai"
email: "alex@helosolutions.ai"
linkedin_username: "your-linkedin"
github_username: "your-github"

# SEO Specific
lang: en_US
social:
  name: Alex Ash
  links:
    - https://twitter.com/alexheloai
    - https://www.linkedin.com/in/your-linkedin
    - https://github.com/your-github

# Jekyll SEO Tag
twitter:
  username: alexheloai
  card: summary_large_image

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "alex@helosolutions.ai"

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
